
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_TODAYS_WEIGHT = 'SET_TODAYS_WEIGHT';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
