
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
export const SET_TODAYS_WEIGHT = 'SET_TODAYS_WEIGHT';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const SET_USER_TOKEN_AND_ID = 'SET_USER_TOKEN_AND_ID';
